#!/bin/sh

# this script makes a backup of important files 
# in home directory. Arguments: destination folder
# the files backed up are described in
# ~/.config/backup/conf, one file/directory
# per line. The backups is done recursively.
# To avoid backing up a file/directory,
# prepend ! to that file/dir name in the config file

# switch to home directory
cd $HOME

# parse the config file
while read directory; do
    if [[ "$directory" =~ '!' ]]; then
        not_to_backup+="-path \"*${directory:1}*\" -prune -o "
    else
        docs_to_backup+="$directory "
    fi
done < ~/.config/backup/conf

# find all filenames to backup and not to backup,
# and save them in a temporary file
command="find $docs_to_backup $not_to_backup -print"
eval "$command" > /tmp/backup
# archive name
archive="$( date +"%Y-%m-%d" )_backup.tar.gz"
# execute the backup
sudo tar --no-recursion -cvz -T /tmp/backup -f $1/$archive
# vim: ft=bash
